### ISSUE TITLE
Passable Product Checklist

### ISSUE THREAD

**Issue by akmadsen** [akmadsen/cpnt-201-group-assignment#28]
Here is what we 'need' to meet the project spec. 

--------------------------------------------------------

- [ ] Have Blog List, Blog and About Page 
- [ ] Social Icons in the Footer 
- [ ] Sass Variables are being used 
- [ ] Sass styles are nested 
- [ ] Sass styles are based on component 
- [ ] UI components are in Sass files 
- [ ] At least 1 mixin in the project  
- [ ] Indentation Correct for HTML & Sass (final deploy) 
- [ ] Code has no merge conflicts 
- [ ] Site is Responsive 
- [ ] Site is hosted on Now
